package transpiler

// TokenType representa o tipo de token léxico identificado.
type TokenType int

const (
	TokenEOF TokenType = iota
	TokenError
	TokenWhitespace
	TokenNewline
	TokenComment
	TokenIdentifier
	TokenKeyword
	TokenString
	TokenRawString
	TokenRune
	TokenNumber
	TokenOperator
	TokenDelimiter
)

// Token representa uma unidade léxica com sua posição no código-fonte.
type Token struct {
	Type   TokenType
	Value  string
	Line   int
	Column int
}

// KeywordsMap mapeia as palavras reservadas do VAMOS-LANG para Golang.
var KeywordsMap = map[string]string{
	"pacote":      "package",
	"principal":   "main",
	"importar":    "import",
	"funcao":      "func",
	"variavel":    "var",
	"constante":   "const",
	"tipo":        "type",
	"estrutura":   "struct",
	"interface":   "interface",
	"mapa":        "map",
	"canal":       "chan",
	"se":          "if",
	"senao":       "else",
	"para":        "for",
	"intervalo":   "range",
	"escolha":     "switch",
	"caso":        "case",
	"padrao":      "default",
	"prosseguir":  "fallthrough",
	"interromper": "break",
	"continuar":   "continue",
	"ir_para":     "goto",
	"retornar":    "return",
	"disparar":    "go",
	"adiar":       "defer",
	"selecionar":  "select",
}

// ReverseKeywordsMap mapeia palavras reservadas do Go para VAMOS-LANG.
var ReverseKeywordsMap = map[string]string{
	"package":     "pacote",
	"main":        "principal",
	"import":      "importar",
	"func":        "funcao",
	"var":         "variavel",
	"const":       "constante",
	"type":        "tipo",
	"struct":      "estrutura",
	"interface":   "interface",
	"map":         "mapa",
	"chan":        "canal",
	"if":          "se",
	"else":        "senao",
	"for":         "para",
	"range":       "intervalo",
	"switch":      "escolha",
	"case":        "caso",
	"default":     "padrao",
	"fallthrough": "prosseguir",
	"break":       "interromper",
	"continue":    "continuar",
	"goto":        "ir_para",
	"return":      "retornar",
	"go":          "disparar",
	"defer":       "adiar",
	"select":      "selecionar",
}

// TypesAndBuiltinsMap mapeia tipos primitivos, valores literais e funções embutidas.
var TypesAndBuiltinsMap = map[string]string{
	// Tipos Primitivos
	"texto":             "string",
	"inteiro":           "int",
	"inteiro8":          "int8",
	"inteiro16":         "int16",
	"inteiro32":         "int32",
	"inteiro64":         "int64",
	"uinteiro":          "uint",
	"uinteiro8":         "uint8",
	"uinteiro16":        "uint16",
	"uinteiro32":        "uint32",
	"uinteiro64":        "uint64",
	"uinteiro_ponteiro": "uintptr",
	"decimal":           "float64",
	"decimal32":         "float32",
	"decimal64":         "float64",
	"complexo64":        "complex64",
	"complexo128":       "complex128",
	"booleano":          "bool",
	"byte":              "byte",
	"runa":              "rune",
	"caractere":         "rune",
	"qualquer":          "any",
	"erro":              "error",

	// Constantes e Valores Literais
	"verdadeiro": "true",
	"falso":      "false",
	"nulo":       "nil",
	"iota":       "iota",

	// Funções Nativas Embutidas (Built-ins)
	"criar":      "make",
	"novo":       "new",
	"adicionar":  "append",
	"anexar":     "append",
	"tamanho":    "len",
	"capacidade": "cap",
	"fechar":     "close",
	"copiar":     "copy",
	"deletar":    "delete",
	"excluir":    "delete",
	"panico":     "panic",
	"recuperar":  "recover",
	"imprimir":   "print",
	"imprimirln": "println",

	// Ponto de entrada padrão
	"principal": "main",
}

// ReverseTypesAndBuiltinsMap mapeia tipos e built-ins do Go para VAMOS-LANG.
var ReverseTypesAndBuiltinsMap = map[string]string{
	"string":      "texto",
	"int":         "inteiro",
	"int8":        "inteiro8",
	"int16":       "inteiro16",
	"int32":       "inteiro32",
	"int64":       "inteiro64",
	"uint":        "uinteiro",
	"uint8":       "uinteiro8",
	"uint16":      "uinteiro16",
	"uint32":      "uinteiro32",
	"uint64":      "uinteiro64",
	"uintptr":     "uinteiro_ponteiro",
	"float32":     "decimal32",
	"float64":     "decimal64",
	"complex64":   "complexo64",
	"complex128":  "complexo128",
	"bool":        "booleano",
	"byte":        "byte",
	"rune":        "runa",
	"any":         "qualquer",
	"error":       "erro",
	"true":        "verdadeiro",
	"false":       "falso",
	"nil":         "nulo",
	"make":        "criar",
	"new":         "novo",
	"append":      "adicionar",
	"len":         "tamanho",
	"cap":         "capacidade",
	"close":       "fechar",
	"copy":        "copiar",
	"delete":      "excluir",
	"panic":       "panico",
	"recover":     "recuperar",
	"print":       "imprimir",
	"println":     "imprimirln",
}

// StdlibImportPathsMap mapeia as strings de importação em PT-BR para caminhos Go no import ("...").
var StdlibImportPathsMap = map[string]string{
	"formatar":      "fmt",
	"tempo":         "time",
	"matematica":    "math",
	"cordas":        "strings",
	"textos":        "strings",
	"so":            "os",
	"sistema":       "os",
	"sincronizar":   "sync",
	"erros":         "errors",
	"io":            "io",
	"leitor":        "bufio",
	"json":          "encoding/json",
	"servidor_http": "net/http",
	"http":          "net/http",
	"contexto":      "context",
	"registrador":   "log",
	"caminho":       "path/filepath",
	"ordenacao":     "sort",
	"teste":         "testing",
	"testing":       "testing",
}

// ReverseStdlibImportsMap mapeia import paths do Go para pacotes PT-BR.
var ReverseStdlibImportsMap = map[string]string{
	"fmt":           "formatar",
	"time":          "tempo",
	"math":          "matematica",
	"strings":       "cordas",
	"os":            "so",
	"sync":          "sincronizar",
	"errors":        "erros",
	"bufio":         "leitor",
	"encoding/json": "json",
	"net/http":      "servidor_http",
	"context":       "contexto",
	"log":           "registrador",
	"path/filepath": "caminho",
	"sort":          "ordenacao",
	"testing":       "teste",
}

// StdlibIdentMap mapeia os identificadores de pacotes em código (ex: servidor_http. -> http., formatar. -> fmt.).
var StdlibIdentMap = map[string]string{
	"formatar":      "fmt",
	"fmt":           "fmt",
	"tempo":         "time",
	"time":          "time",
	"matematica":    "math",
	"math":          "math",
	"cordas":        "strings",
	"textos":        "strings",
	"strings":       "strings",
	"so":            "os",
	"sistema":       "os",
	"os":            "os",
	"sincronizar":   "sync",
	"sync":          "sync",
	"erros":         "errors",
	"errors":        "errors",
	"io":            "io",
	"leitor":        "bufio",
	"bufio":         "bufio",
	"json":          "json",
	"servidor_http": "http",
	"http":          "http",
	"contexto":      "context",
	"context":       "context",
	"registrador":   "log",
	"log":           "log",
	"caminho":       "filepath",
	"filepath":      "filepath",
	"ordenacao":     "sort",
	"sort":          "sort",
	"teste":         "testing",
	"testing":       "testing",
}

// StdlibMethodsMap mapeia métodos/funções conhecidos para o identificador do pacote Go.
var StdlibMethodsMap = map[string]map[string]string{
	"fmt": {
		"ImprimirLinha":      "Println",
		"ImprimirFormatado":  "Printf",
		"Imprimir":           "Print",
		"FormatarLinha":      "Sprintln",
		"Formatar":           "Sprintf",
		"FormatarSimples":    "Sprint",
		"CriarErro":          "Errorf",
		"ErroFormatado":      "Errorf",
		"Escanear":           "Scan",
		"EscanearLinha":      "Scanln",
		"EscanearFormatado":  "Scanf",
		"Fimprimir":          "Fprint",
		"FimprimirLinha":     "Fprintln",
		"FimprimirFormatado": "Fprintf",
	},
	"time": {
		"Dormir":              "Sleep",
		"Agora":               "Now",
		"Segundo":             "Second",
		"Milissegundo":        "Millisecond",
		"Microssegundo":       "Microsecond",
		"Nanosegundo":         "Nanosecond",
		"Minuto":              "Minute",
		"Hora":                "Hour",
		"Duracao":             "Duration",
		"Desde":               "Since",
		"Apos":                "After",
		"NovoTemporizador":    "NewTimer",
		"NovoTique":           "NewTicker",
		"Tique":               "Tick",
		"Data":                "Date",
		"CarregarLocalizacao": "LoadLocation",
		"FormatoUnix":         "Unix",
	},
	"math": {
		"Pi":        "Pi",
		"Raiz":      "Sqrt",
		"Potencia":  "Pow",
		"Absoluto":  "Abs",
		"Piso":      "Floor",
		"Teto":      "Ceil",
		"Maximo":    "Max",
		"Minimo":    "Min",
		"Seno":      "Sin",
		"Cosseno":   "Cos",
		"Tangente":  "Tan",
		"Logaritmo": "Log",
		"Mod":       "Mod",
	},
	"strings": {
		"Contem":         "Contains",
		"Dividir":        "Split",
		"Juntar":         "Join",
		"ParaMaiusculas": "ToUpper",
		"ParaMinusculas": "ToLower",
		"Substituir":     "Replace",
		"SubstituirTudo": "ReplaceAll",
		"TemPrefixo":     "HasPrefix",
		"TemSufixo":      "HasSuffix",
		"Aparar":         "Trim",
		"ApararEspaco":   "TrimSpace",
		"Indice":         "Index",
		"Repetir":        "Repeat",
		"Contar":         "Count",
		"Comparar":       "Compare",
		"IgualDobra":     "EqualFold",
	},
	"sync": {
		"GrupoEspera":         "WaitGroup",
		"Trava":               "Mutex",
		"TravaLeituraEscrita": "RWMutex",
		"UmaVez":              "Once",
		"Condicao":            "Cond",
		"NovoCondicao":        "NewCond",
	},
	"errors": {
		"Novo":         "New",
		"Desempacotar": "Unwrap",
		"E":            "Is",
		"Como":         "As",
		"Juntar":       "Join",
	},
	"os": {
		"Sair":                    "Exit",
		"Argumentos":              "Args",
		"LerArquivo":              "ReadFile",
		"EscreverArquivo":         "WriteFile",
		"ObterVariavelAmbiente":   "Getenv",
		"DefinirVariavelAmbiente": "Setenv",
		"CriarDiretorio":          "Mkdir",
		"CriarTodosDiretorios":    "MkdirAll",
		"Remover":                 "Remove",
		"RemoverTodos":            "RemoveAll",
		"Abrir":                   "Open",
		"Criar":                   "Create",
		"Arquivo":                 "File",
		"EntradaPadrao":           "Stdin",
		"SaidaPadrao":             "Stdout",
		"ErroPadrao":              "Stderr",
		"ObterDiretorioAtual":     "Getwd",
		"MudarDiretorio":          "Chdir",
		"NomeHost":                "Hostname",
	},
	"log": {
		"ImprimirLinha":     "Println",
		"ImprimirFormatado": "Printf",
		"Imprimir":          "Print",
		"Fatal":             "Fatal",
		"FatalFormatado":    "Fatalf",
		"FatalLinha":        "Fatalln",
		"Panico":            "Panic",
		"PanicoFormatado":   "Panicf",
		"PanicoLinha":       "Panicln",
	},
	"http": {
		"OuvirEServir":            "ListenAndServe",
		"Manipulador":             "HandleFunc",
		"NovoRequisicao":          "NewRequest",
		"Cliente":                 "Client",
		"Resposta":                "Response",
		"Requisicao":              "Request",
		"EscritorResposta":        "ResponseWriter",
		"StatusOk":                "StatusOK",
		"StatusCriado":            "StatusCreated",
		"StatusNaoEncontrado":     "StatusNotFound",
		"StatusErroInterno":       "StatusInternalServerError",
		"StatusRequisicaoInvalida": "StatusBadRequest",
		"Obter":                   "Get",
		"Postar":                  "Post",
	},
	"json": {
		"Serializar":         "Marshal",
		"SerializarIdentado": "MarshalIndent",
		"Deserializar":       "Unmarshal",
		"NovoCodificador":    "NewEncoder",
		"NovoDecodificador":  "NewDecoder",
	},
	"bufio": {
		"NovoScanner":  "NewScanner",
		"NovoLeitor":   "NewReader",
		"NovoEscritor": "NewWriter",
	},
	"filepath": {
		"Juntar":            "Join",
		"Base":              "Base",
		"Diretorio":         "Dir",
		"Absoluto":          "Abs",
		"Extensao":          "Ext",
		"Limpar":            "Clean",
		"Caminhar":          "Walk",
		"CaminharDiretorio": "WalkDir",
		"Corresponder":      "Match",
		"Relativo":          "Rel",
	},
	"sort": {
		"Strings":      "Strings",
		"Inteiros":     "Ints",
		"Decimais":     "Float64s",
		"EstaOrdenado": "StringsAreSorted",
		"Fatia":        "Slice",
		"FatiaEstavel": "SliceStable",
	},
	"context": {
		"PlanoDeFundo":    "Background",
		"TODO":            "TODO",
		"ComCancelamento": "WithCancel",
		"ComTempoLimite":  "WithTimeout",
		"ComPrazo":        "WithDeadline",
		"ComValor":        "WithValue",
	},
	"testing": {
		"Erro":           "Error",
		"ErroFormatado":  "Errorf",
		"Fatal":          "Fatal",
		"FatalFormatado": "Fatalf",
		"Falhar":         "Fail",
		"FalhaAgora":     "FailNow",
		"Log":            "Log",
		"LogFormatado":   "Logf",
		"Executar":       "Run",
		"Pular":          "Skip",
		"PularAgora":     "SkipNow",
	},
}

// MethodAliasesMap mapeia nomes de métodos de objetos e interfaces em PT-BR para Go.
var MethodAliasesMap = map[string]string{
	"Adicionar":      "Add",
	"Concluido":      "Done",
	"Feito":          "Done",
	"Esperar":        "Wait",
	"Bloquear":       "Lock",
	"Desbloquear":    "Unlock",
	"Fechar":         "Close",
	"Ler":            "Read",
	"Escrever":       "Write",
	"Texto":          "String",
	"Erro":           "Error",
	"Formato":        "Format",
	"Formatar":       "Format",
	"Unix":           "Unix",
	"Segundos":       "Seconds",
	"Milissegundos":  "Milliseconds",
	"Microssegundos": "Microseconds",
	"Nanosegundos":   "Nanoseconds",
	"Minutos":        "Minutes",
	"Horas":          "Hours",
}

// ReverseMethodAliasesMap mapeia métodos Go para PT-BR.
var ReverseMethodAliasesMap = map[string]string{
	"Add":          "Adicionar",
	"Done":         "Concluido",
	"Wait":         "Esperar",
	"Lock":         "Bloquear",
	"Unlock":       "Desbloquear",
	"Close":        "Fechar",
	"Read":         "Ler",
	"Write":        "Escrever",
	"String":       "Texto",
	"Error":        "Erro",
	"Format":       "Formato",
	"Milliseconds": "Milissegundos",
	"Seconds":      "Segundos",
}
